/* GRTeclyn
 * Copyright 2022 The GRTL collaboration.
 * Please refer to LICENSE in GRTeclyn's root directory.
 */

// Reference RHS values for the FourDerivScalarTensorTest probe cell.
//
// This file is #included inside run_four_deriv_scalar_tensor_test(), where
//   std::array<amrex::Real, NUM_VARS> known;   // zero-initialised
//   bool have_reference;
// are in scope. Fill one "known[c_<var>] = <number>;" line per component and
// set have_reference = true.
//
// HOW TO REGENERATE
// -----------------
// 1. Build GRChombo/Tests/FourDerivScalarTensorGridTest (needs a GRChombo +
//    GRFolres checkout with CHOMBO_HOME / GRCHOMBO_SOURCE set), e.g.
//       cd GRFolres/GRChombo/Tests/FourDerivScalarTensorGridTest && make all
// 2. Run the executable; it prints a "known[c_...] = ...;" block followed by
//    "have_reference = true;" for the same grid, parameters and constant
//    coupling used by this test.
// 3. Replace everything below this line with that output.
//
// Until then the test still builds and runs: it reports the computed RHS and
// only checks that it contains no NaNs.

// --- paste GRChombo output below ------------------
// --- generated by GRChombo/Tests/FourDerivScalarTensorGridTest ---
known[c_chi] = -0.009665850537308486;
known[c_h11] = 0.077215081736794852;
known[c_h12] = -0.26255378975816362;
known[c_h13] = 0.763206307821509;
known[c_h22] = 2.0075810443064834;
known[c_h23] = -0.39523088040457088;
known[c_h33] = -1.5974440491390234;
known[c_K] = -5.2405593428480843;
known[c_A11] = 2.6892779835026617;
known[c_A12] = -1.0196733398510982;
known[c_A13] = 0.30180561942860668;
known[c_A22] = 1.5310796563724201;
known[c_A23] = -1.1228457302515762;
known[c_A33] = -3.1958082724923775;
known[c_Theta] = 11.449416630060398;
known[c_Gamma1] = -27.888485804121153;
known[c_Gamma2] = 22.024110448379087;
known[c_Gamma3] = -60.99688648322222;
known[c_lapse] = 2.2092014051310045;
known[c_shift1] = -0.3278874206586061;
known[c_shift2] = -0.29244895630792861;
known[c_shift3] = -0.50758426357947328;
known[c_B1] = 0;
known[c_B2] = 0;
known[c_B3] = 0;
known[c_phi] = 0.82616085843342346;
known[c_Pi] = 1.5482218213690579;
have_reference = true;

